version: 2

sources:
  - name: coffee_shop
    project: analytics-engineers-club
    description: AEC dataset, currently a stale dataset.
    freshness:
      error_after:
        count: 12
        period: hour
    loaded_at_field: created_at
    tables:
      - name: customers
        description: Customer identification details, unique per customer
        columns:
          - name: id
            tests:
              - unique
              - not_null
      - name: orders
        description: Order details, unique per order
        columns:
          - name: id
            tests:
              - unique
              - not_null